name: flutter_fancy_tree_view
description: >
  A highly customizable TreeView Widget for visualization of nested data in
  Flutter.
version: 0.5.2
homepage: https://mbaumgartenbr.github.io/flutter_tree_view
repository: https://github.com/mbaumgartenbr/flutter_tree_view

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: "1.0.4"
  flutter_test:
    sdk: flutter
